/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'README',
    'import-existing-project',
    'cli',
    {
      type: 'category',
      label: 'Configuration',
      items: [
        'config/configuration',
        {
          type: 'category',
          label: 'Plugins',
          link: {
            type: 'doc',
            id: 'config/plugins/README',
          },
          items: [
            'config/plugins/webpack',
            'config/plugins/vite',
            'config/plugins/electronegativity',
            'config/plugins/auto-unpack-natives',
            'config/plugins/local-electron',
            'config/plugins/fuses',
          ],
        },
        {
          type: 'category',
          label: 'Makers',
          items: [
            'config/makers/appx',
            'config/makers/deb',
            'config/makers/dmg',
            'config/makers/flatpak',
            'config/makers/pkg',
            'config/makers/README',
            'config/makers/rpm',
            'config/makers/snapcraft',
            'config/makers/squirrel.windows',
            'config/makers/wix-msi',
            'config/makers/zip',
          ],
        },
        {
          type: 'category',
          label: 'Publishers',
          items: [
            'config/publishers/bitbucket',
            'config/publishers/electron-release-server',
            'config/publishers/gcs',
            'config/publishers/github',
            'config/publishers/nucleus',
            'config/publishers/README',
            'config/publishers/s3',
            'config/publishers/snapcraft',
          ],
        },
        'config/hooks',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        'core-concepts/why-electron-forge',
        'core-concepts/build-lifecycle',
      ],
    },
    {
      type: 'category',
      label: 'Templates',
      items: [
        'templates/vite',
        'templates/vite-+-typescript',
        'templates/webpack-template',
        'templates/typescript-+-webpack-template',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'category',
          label: 'Code Signing',
          items: [
            'guides/code-signing/code-signing-windows',
            'guides/code-signing/code-signing-macos',
          ],
        },
        'guides/create-and-add-icons',
        {
          type: 'category',
          label: 'Framework Integration',
          items: [
            'guides/framework-integration/parcel',
            'guides/framework-integration/react',
            'guides/framework-integration/react-with-typescript',
            'guides/framework-integration/vue-3',
          ],
        },
        'guides/developing-with-wsl',
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [
        'advanced/auto-update',
        'advanced/debugging',
        {
          type: 'category',
          label: 'Extending Electron Forge',
          items: [
            'advanced/extending-electron-forge/writing-plugins',
            'advanced/extending-electron-forge/writing-templates',
            'advanced/extending-electron-forge/writing-makers',
            'advanced/extending-electron-forge/writing-publishers',
          ],
        },
      ],
    },
    {
      type: 'link',
      label: 'API Docs',
      href: 'https://js.electronforge.io/modules/_electron_forge_core.html',
    },
  ],

};

module.exports = sidebars;
